exports.PERM_TEAMS_DATA_ACCESS = 1;
exports.PERM_ADD_GAME = 2;
exports.PERM_ALL_GAME_ACCESS = 3;
exports.PERM_ALL_GAME_ADMIN = 4;
exports.PERM_EDIT_ASSIGNED_GAME = 5;
exports.PERM_SCORE_TABLE_ACCESS = 6;
exports.PERM_SYSTEM_ADMIN = 8;
